# Generated by Django 3.1.7 on 2021-06-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0002_recruitdeveloper'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitHr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=2)),
                ('MoblileNo', models.CharField(max_length=10)),
                ('EmailId', models.CharField(max_length=30)),
                ('WorkExperience', models.CharField(max_length=2)),
                ('Specialization', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50)),
                ('UserId', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
    ]
