# Generated by Django 3.1.7 on 2021-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0003_recruithr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitDeveloperAsProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20)),
                ('UserId', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
