# Generated by Django 3.1.7 on 2021-06-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0005_addclientsandprojectsbymyadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitdeveloperasprojectmanager',
            old_name='Password',
            new_name='DevsId',
        ),
    ]
