# Generated by Django 3.1.7 on 2021-06-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0008_assignprojecttoprojectmanagerbymyadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitdeveloper',
            old_name='MoblileNo',
            new_name='MobileNo',
        ),
    ]
