# Generated by Django 3.1.7 on 2021-06-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0009_auto_20210624_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruithr',
            old_name='MoblileNo',
            new_name='MobileNo',
        ),
    ]
