# Generated by Django 3.1.7 on 2021-06-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0012_activeadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=15)),
            ],
        ),
    ]
