# Generated by Django 3.1.7 on 2021-06-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuest', '0014_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='ReportById',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reports',
            name='ReportToId',
            field=models.CharField(max_length=20),
        ),
    ]
